package com.ivarna.fluxlinux.core.terminal

import android.content.Context
import android.util.Log
import com.ivarna.fluxlinux.BuildConfig
import java.io.File

/**
 * Single source of truth for host (embedded Termux-class) package paths.
 *
 * Kotlin, generated `fluxlinux-host.env`, and bootstrap path rewrites all derive
 * from [PACKAGE]. Never hardcode `com.termux` defaults at call sites.
 * Mirrors termux-lib `TermuxHostPaths` with the package pinned to the flavor
 * applicationId via `BuildConfig.APPLICATION_ID`.
 */
object TermuxHostPaths {
    val PACKAGE: String get() = BuildConfig.APPLICATION_ID
    const val STOCK_PACKAGE = "com.termux"

    /** `/data/data/<package>` */
    val DATA_ROOT: String get() = "/data/data/$PACKAGE"
    val STOCK_DATA_ROOT: String get() = "/data/data/$STOCK_PACKAGE"

    val FILES: String get() = "$DATA_ROOT/files"
    val PREFIX: String get() = "$FILES/usr"
    val HOME: String get() = "$FILES/home"
    val TMPDIR: String get() = "$PREFIX/tmp"
    val BIN: String get() = "$PREFIX/bin"
    val LIB: String get() = "$PREFIX/lib"
    val SSL_CERT: String get() = "$PREFIX/etc/tls/cert.pem"
    val PROOT_DISTRO: String get() = "$BIN/proot-distro"
    const val TERMUX_VERSION = "flux-host"

    /** Relative path under app filesDir for generated shell env. */
    const val HOST_ENV_REL = "usr/etc/fluxlinux-host.env"

    private const val TAG = "TermuxHostPaths"
    private const val MAX_REWRITE_BYTES = 2_000_000L

    fun setupTermuxMarker(ctx: Context): File =
        File(ctx.filesDir, "home/.fluxlinux/setup_termux.done")

    fun clearSetupTermuxMarker(ctx: Context): Boolean =
        setupTermuxMarker(ctx).delete()

    fun libProot(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libproot.so")

    fun libLoader(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libloader.so")

    fun libLoader32(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libloader32.so")

    fun libBash(ctx: Context): File =
        File(ctx.applicationInfo.nativeLibraryDir, "libbash.so")

    fun termuxExec(ctx: Context): File =
        File(ctx.filesDir, "usr/lib/libtermux-exec.so")

    fun homeDir(ctx: Context): File =
        File(ctx.filesDir, "home")

    fun hostScript(ctx: Context, name: String): File =
        File(homeDir(ctx), name)

    fun hostEnvFile(filesDir: File): File =
        File(filesDir, HOST_ENV_REL)

    /** Relative path under filesDir for proot-distro login __init__.py (W^X patch target). */
    const val PROOT_DISTRO_LOGIN_INIT_REL =
        "usr/lib/python3.14/site-packages/proot_distro/commands/login/__init__.py"

    /** Replace stock Termux data-root paths with this package's paths. */
    fun rewriteStockPaths(text: String): String =
        text.replace(STOCK_DATA_ROOT, DATA_ROOT)

    /**
     * Write `usr/etc/fluxlinux-host.env` for shell scripts to source.
     * Generated from this object only — do not hand-edit on device.
     *
     * When [ctx] is provided, also pins W^X-safe `PD_PROOT_BIN` / `PROOT_LOADER{,_32}`
     * to jniLibs under `nativeLibraryDir` (required on targetSdk 36).
     */
    fun writeHostEnvFile(filesDir: File, ctx: Context? = null): File {
        val f = hostEnvFile(filesDir)
        f.parentFile?.mkdirs()
        val wxBlock = if (ctx != null) {
            """
            |export PD_PROOT_BIN="${libProot(ctx).absolutePath}"
            |export PROOT_LOADER="${libLoader(ctx).absolutePath}"
            |export PROOT_LOADER_32="${libLoader32(ctx).absolutePath}"
            |""".trimMargin()
        } else {
            ""
        }
        f.writeText(
            """
            |# Generated by TermuxHostPaths.kt — single source of truth. Do not edit.
            |export TERMUX_APP__PACKAGE_NAME="$PACKAGE"
            |export TERMUX_X11_OVERRIDE_PACKAGE="$PACKAGE"
            |export TERMUX__PREFIX="$PREFIX"
            |export TERMUX__HOME="$HOME"
            |export PREFIX="$PREFIX"
            |export HOME="$HOME"
            |export TMPDIR="$TMPDIR"
            |export PROOT_TMP_DIR="$TMPDIR"
            |export TERMUX_VERSION="$TERMUX_VERSION"
            |export SSL_CERT_FILE="$SSL_CERT"
            |export CURL_CA_BUNDLE="$SSL_CERT"
            |export PATH="$BIN:$BIN/applets:/system/bin:/system/xbin${'$'}{PATH:+:${'$'}PATH}"
            |export LD_LIBRARY_PATH="$LIB${'$'}{LD_LIBRARY_PATH:+:${'$'}LD_LIBRARY_PATH}"
            |$wxBlock
            |""".trimMargin()
        )
        return f
    }

    /**
     * Patch proot-distro so `PROOT_LOADER` / `PROOT_LOADER_32` are passed through
     * to the proot process. Stock only allows `PROOT_NO_SECCOMP` / `PROOT_VERBOSE`;
     * without the loader env, proot falls back to `$PREFIX/libexec/proot/loader`
     * which is not executable under targetSdk 36 W^X →
     * `proot error: execve("/usr/bin/bash"): Permission denied`.
     *
     * Idempotent — safe to call on every host prepare.
     * Mirrors termux-lib OnboardingActivity post-extract patch.
     *
     * @return true when the file was patched (or already patched)
     */
    fun patchProotDistroLoaderPassThrough(filesDir: File): Boolean {
        val loginInit = File(filesDir, PROOT_DISTRO_LOGIN_INIT_REL)
        if (!loginInit.isFile) {
            Log.w(TAG, "proot-distro login __init__.py missing: ${loginInit.absolutePath}")
            return false
        }
        return try {
            var content = loginInit.readText(Charsets.UTF_8)
            val stock = "\"PROOT_NO_SECCOMP\", \"PROOT_VERBOSE\""
            val patched = "\"PROOT_NO_SECCOMP\", \"PROOT_VERBOSE\", \"PROOT_LOADER\", \"PROOT_LOADER_32\""
            // Already fully patched
            if (content.contains("\"PROOT_LOADER\"") && content.contains("\"PROOT_LOADER_32\"")) {
                return true
            }
            // Partial (termux-lib style PROOT_LOADER only) → upgrade to include _32
            if (content.contains("\"PROOT_NO_SECCOMP\", \"PROOT_VERBOSE\", \"PROOT_LOADER\"") &&
                !content.contains("\"PROOT_LOADER_32\"")
            ) {
                content = content.replace(
                    "\"PROOT_NO_SECCOMP\", \"PROOT_VERBOSE\", \"PROOT_LOADER\"",
                    patched
                )
                loginInit.writeText(content, Charsets.UTF_8)
                Log.i(TAG, "upgraded proot-distro PROOT_LOADER pass-through (+PROOT_LOADER_32)")
                return true
            }
            if (!content.contains(stock)) {
                Log.w(TAG, "proot-distro allowlist pattern not found; cannot patch PROOT_LOADER")
                return false
            }
            content = content.replace(stock, patched)
            loginInit.writeText(content, Charsets.UTF_8)
            Log.i(TAG, "patched proot-distro to pass PROOT_LOADER / PROOT_LOADER_32")
            true
        } catch (e: Exception) {
            Log.e(TAG, "failed to patch proot-distro PROOT_LOADER pass-through", e)
            false
        }
    }

    /**
     * After bootstrap extract (and before host setup): rewrite residual
     * `/data/data/com.termux/...` text under the prefix, patch proot-distro
     * W^X loader pass-through, then write host env file.
     *
     * @param ctx optional; when set, host env also pins PD_PROOT_BIN / PROOT_LOADER*
     * @return number of stock-path files rewritten
     */
    fun applyPackageToExtractedPrefix(filesDir: File, ctx: Context? = null): Int {
        var rewritten = 0
        val roots = listOf(
            File(filesDir, "usr/bin"),
            File(filesDir, "usr/etc"),
            File(filesDir, "usr/share"),
            File(filesDir, "usr/lib/python3.14/site-packages/proot_distro"),
            File(filesDir, "usr/include/termux-exec"),
        )
        for (root in roots) {
            if (!root.exists()) continue
            root.walkTopDown().forEach { file ->
                if (!file.isFile) return@forEach
                val len = file.length()
                if (len == 0L || len > MAX_REWRITE_BYTES) return@forEach
                try {
                    val bytes = file.readBytes()
                    // Skip binaries (NUL in first 512 bytes)
                    val scan = minOf(bytes.size, 512)
                    for (i in 0 until scan) {
                        if (bytes[i] == 0.toByte()) return@forEach
                    }
                    val text = bytes.toString(Charsets.UTF_8)
                    if (!text.contains(STOCK_DATA_ROOT)) return@forEach
                    file.writeText(rewriteStockPaths(text), Charsets.UTF_8)
                    rewritten++
                } catch (e: Exception) {
                    Log.w(TAG, "skip rewrite ${file.absolutePath}: ${e.message}")
                }
            }
        }
        // W^X: must run after any rewrite of proot_distro tree (and every prepareHost).
        patchProotDistroLoaderPassThrough(filesDir)
        writeHostEnvFile(filesDir, ctx)
        // Ensure proot temp dir exists (proot fails with chmod ENOENT if missing).
        File(filesDir, "usr/tmp").mkdirs()
        if (rewritten > 0) {
            Log.i(TAG, "rewrote $rewritten file(s): $STOCK_DATA_ROOT → $DATA_ROOT")
        }
        return rewritten
    }
}
